### ISSUE TITLE
0x6E5e17B29365AF1637234Fe7fb813f59d845122d

### ISSUE THREAD

**Issue by Falehfaleh** [ethereum/beacon-APIs#363]
Faleh btcst
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
- [ ] https://github.com/ethereum/beacon-APIs/pull/270
- [ ] https://github.com/ethereum/beacon-APIs/pull/357
- [ ] https://github.com/ethereum/beacon-APIs/pull/339
- [ ] https://github.com/ethereum/beacon-APIs/pull/355
- [ ] https://github.com/ethereum/beacon-APIs/pull/353
- [ ] https://github.com/ethereum/beacon-APIs/pull/356
- [ ] https://github.com/ethereum/beacon-APIs/pull/350
- [ ] https://github.com/ethereum/beacon-APIs/issues/348
- [ ] https://github.com/ethereum/beacon-APIs/issues/333
- [ ] https://github.com/ethereum/beacon-APIs/pull/317
- [ ] https://github.com/ethereum/beacon-APIs/issues/322
- [ ] https://github.com/ethereum/beacon-APIs/pull/344
- [ ] https://github.com/ethereum/beacon-APIs/pull/343
- [ ] https://github.com/ethereum/beacon-APIs/pull/340
- [ ] https://github.com/ethereum/beacon-APIs/issues/308
- [ ] https://github.com/ethereum/beacon-APIs/issues/292
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
- [ ] https://github.com/ethereum/beacon-APIs/pull/270
- [ ] https://github.com/ethereum/beacon-APIs/pull/357
- [ ] https://github.com/ethereum/beacon-APIs/pull/339
- [ ] https://github.com/ethereum/beacon-APIs/pull/355
- [ ] https://github.com/ethereum/beacon-APIs/issues/348
- [ ] https://github.com/ethereum/beacon-APIs/issues/333
- [ ] https://github.com/ethereum/beacon-APIs/issues/322
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
- [ ] https://github.com/ethereum/beacon-APIs/pull/270
- [ ] https://github.com/ethereum/beacon-APIs/pull/357
- [ ] https://github.com/ethereum/beacon-APIs/pull/339
- [ ] https://github.com/ethereum/beacon-APIs/pull/355
- [ ] https://github.com/ethereum/beacon-APIs/pull/353
- [ ] https://github.com/ethereum/beacon-APIs/pull/356
- [ ] https://github.com/ethereum/beacon-APIs/pull/350
- [ ] https://github.com/ethereum/beacon-APIs/issues/348
- [ ] https://github.com/ethereum/beacon-APIs/issues/333
- [ ] https://github.com/ethereum/beacon-APIs/pull/317
- [ ] https://github.com/ethereum/beacon-APIs/issues/322
- [ ] https://github.com/ethereum/beacon-APIs/pull/344
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
- [ ] https://github.com/ethereum/beacon-APIs/pull/270
- [ ] https://github.com/ethereum/beacon-APIs/pull/357
- [ ] https://github.com/ethereum/beacon-APIs/pull/339
- [ ] https://github.com/ethereum/beacon-APIs/pull/355
```

**Comment by michaelsproul** [comment]
No.

**Comment by Falehfaleh** [comment]
Faleh
