### ISSUE TITLE
F

### ISSUE THREAD

**Issue by Falehfale** [ethereum/beacon-APIs#364]
H
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/pull/254
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/issues/363
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
- [ ] https://github.com/ethereum/beacon-APIs/pull/270
- [ ] https://github.com/ethereum/beacon-APIs/pull/357
- [ ] https://github.com/ethereum/beacon-APIs/pull/339
- [ ] https://github.com/ethereum/beacon-APIs/pull/355
- [ ] https://github.com/ethereum/beacon-APIs/pull/353
- [ ] https://github.com/ethereum/beacon-APIs/pull/356
- [ ] https://github.com/ethereum/beacon-APIs/pull/350
- [ ] https://github.com/ethereum/beacon-APIs/issues/348
- [ ] https://github.com/ethereum/beacon-APIs/issues/333
- [ ] https://github.com/ethereum/beacon-APIs/pull/317
- [ ] https://github.com/ethereum/beacon-APIs/issues/322
- [ ] https://github.com/ethereum/beacon-APIs/pull/343
- [ ] https://github.com/ethereum/beacon-APIs/pull/344
- [ ] https://github.com/ethereum/beacon-APIs/pull/340
- [ ] https://github.com/ethereum/beacon-APIs/issues/308
- [ ] https://github.com/ethereum/beacon-APIs/issues/292
- [ ] https://github.com/ethereum/beacon-APIs/issues/193
- [ ] https://github.com/ethereum/beacon-APIs/issues/42
- [ ] https://github.com/ethereum/beacon-APIs/pull/342
- [ ] https://github.com/ethereum/beacon-APIs/pull/341
- [ ] https://github.com/ethereum/beacon-APIs/pull/338
- [ ] https://github.com/ethereum/beacon-APIs/pull/331
- [ ] https://github.com/ethereum/beacon-APIs/pull/336
- [ ] https://github.com/ethereum/beacon-APIs/pull/328
- [ ] https://github.com/ethereum/beacon-APIs/pull/334
- [ ] https://github.com/ethereum/beacon-APIs/pull/170
- [ ] https://github.com/ethereum/beacon-APIs/pull/329
- [ ] https://github.com/ethereum/beacon-APIs/pull/330
- [ ] https://github.com/ethereum/beacon-APIs/issues/186
- [ ] https://github.com/ethereum/beacon-APIs/issues/337
- [ ] https://github.com/ethereum/beacon-APIs/issues/332
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/pull/358
- [ ] https://github.com/ethereum/beacon-APIs/pull/362
- [ ] https://github.com/ethereum/beacon-APIs/issues/363
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
- [ ] https://github.com/ethereum/beacon-APIs/pull/270
- [ ] https://github.com/ethereum/beacon-APIs/pull/357
- [ ] https://github.com/ethereum/beacon-APIs/pull/356
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/beacon-APIs/issues/349
- [ ] https://github.com/ethereum/beacon-APIs/issues/361
```
